### ISSUE TITLE
分p视频音频下载

### ISSUE THREAD

**Issue by gongqiong** [Youguang-Zhou/bilibili-dl#2]
请问分p视频如何下载全部分p的音频呢？

**Comment by Youguang-Zhou** [comment]
你好，感谢提出issue，目前已经更新了3.1.0版本，更新之后就可以下载分p视频下的所有音视频了。

从pip上更新：
```
pip install -U bilibili-dl
```
下载该BV号下所有分p视频的音频（分p视频共用一个BV号）：
```
bilibili-dl [bvid] -a
```

把 [bvid] 替换为你要下载的bv号，-a表示仅下载音频。
